<?php

namespace Fatchip\FCSPayment;

/**
 * Class CTPaymentMethods
 * @package Fatchip\FCSPayment
 */
class CTPaymentMethods
{
    const paymentMethods =
        [
            [
                'name' => 'fatchip_firstcash_creditcard',
                'shortname' => 'Kreditkarte',
                'description' => 'First Cash Solution Kreditkarte',
                'action' => 'FatchipFCSCreditCard',
                'template' => '',
                'additionalDescription' => '',
                'className' => 'CreditCard',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_firstcash_easycredit',
                'shortname' => 'Easycredit',
                'description' => 'First Cash Solution Easycredit',
                'action' => 'FatchipFCSEasyCredit',
                'template' => 'fatchip_firstcash_easycredit.tpl',
                'additionalDescription' => 'Rechnungs- und Lieferadresse müssen gleich sein, damit easyCredit genutzt werden kann',
                'className' => 'EasyCredit',
                // 'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_firstcash_ideal',
                'shortname' => 'iDEAL',
                'description' => 'First Cash Solution iDEAL',
                'action' => 'FatchipFCSIdeal',
                'template' => 'fatchip_firstcash_ideal.tpl',
                'additionalDescription' => '',
                'className' => 'Ideal',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_firstcash_klarna_slice_it',
                'shortname' => 'Klarna Slice it',
                'description' => 'First Cash Solution Klarna Slice it',
                'action' => 'FatchipFCSKlarnaPayments',
                'template' => 'fatchip_firstcash_klarna_slice_it.tpl',
                'additionalDescription' => '',
                'className' => 'KlarnaPayments',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_firstcash_klarna_pay_now',
                'shortname' => 'Klarna Pay now',
                'description' => 'First Cash Solution Klarna Pay now',
                'action' => 'FatchipFCSKlarnaPayments',
                'template' => 'fatchip_firstcash_klarna_pay_now.tpl',
                'additionalDescription' => '',
                'className' => 'KlarnaPayments',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_firstcash_klarna_pay_later',
                'shortname' => 'Klarna Pay later',
                'description' => 'First Cash Solution Klarna Pay later',
                'action' => 'FatchipFCSKlarnaPayments',
                'template' => 'fatchip_firstcash_klarna_pay_later.tpl',
                'additionalDescription' => '',
                'className' => 'KlarnaPayments',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_firstcash_klarna_direct_bank_transfer',
                'shortname' => 'Klarna Sofort',
                'description' => 'First Cash Solution Klarna Sofort',
                'action' => 'FatchipFCSKlarnaPayments',
                'template' => 'fatchip_firstcash_klarna_direct_bank_transfer.tpl',
                'additionalDescription' => '',
                'className' => 'KlarnaPayments',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_firstcash_klarna_direct_debit',
                'shortname' => 'Klarna Lastschrift',
                'description' => 'First Cash Solution Klarna Lastschrift',
                'action' => 'FatchipFCSKlarnaPayments',
                'template' => 'fatchip_firstcash_klarna_direct_debit.tpl',
                'additionalDescription' => '',
                'className' => 'KlarnaPayments',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_firstcash_lastschrift',
                'shortname' => 'Lastschrift',
                'description' => 'First Cash Solution Lastschrift',
                'action' => 'FatchipFCSLastschrift',
                'template' => 'fatchip_firstcash_lastschrift.tpl',
                'additionalDescription' => '',
                'className' => 'Lastschrift',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_firstcash_paydirekt',
                'shortname' => 'Paydirekt',
                'description' => 'First Cash Solution Paydirekt',
                'action' => 'FatchipFCSPaydirekt',
                'template' => '',
                'additionalDescription' => '',
                'className' => 'Paydirekt',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_firstcash_paypal_standard',
                'shortname' => 'PayPal',
                'description' => 'First Cash Solution PayPal Standard',
                'action' => 'FatchipFCSPaypalStandard',
                'template' => '',
                'additionalDescription' => '',
                'className' => 'PaypalStandard',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_firstcash_paypal_express',
                'shortname' => 'PayPalExpress',
                'description' => 'First Cash Solution PayPal Express',
                'action' => 'FatchipFCSPaypalExpress',
                'template' => '',
                'additionalDescription' => '',
                'className' => 'PaypalExpress',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
/*            [
                'name' => 'fatchip_firstcash_postfinance',
                'shortname' => 'Postfinance',
                'description' => 'First Cash Solution Postfinance',
                'action' => 'FatchipFCSPostFinance',
                'template' => '',
                'additionalDescription' => '',
                'className' => 'PostFinance',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],*/
/*            [
                'name' => 'fatchip_firstcash_przelewy24',
                'shortname' => 'Przelewy24',
                'description' => 'First Cash Solution Przelewy24',
                'action' => 'FatchipFCSPrzelewy24',
                'countries' => ['PL',],
                'template' => '',
                'additionalDescription' => '',
                'className' => 'Przelewy24',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],*/
            [
                'name' => 'fatchip_firstcash_sofort',
                'shortname' => 'SOFORT',
                'description' => 'First Cash Solution SOFORT',
                'action' => 'FatchipFCSSofort',
                //'template' => 'fatchip_firstcash_sofort.tpl',
                'template' => '',
                'additionalDescription' => '',
                'className' => 'Sofort',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
            [
                'name' => 'fatchip_firstcash_amazonpay',
                'shortname' => 'AmazonPay',
                'description' => 'First Cash Solution AmazonPay',
                'action' => 'FatchipFCSAmazon',
                'template' => '',
                'additionalDescription' => '',
                'className' => 'AmazonPay',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
/*            [
                'name' => 'fatchip_firstcash_afterpay_invoice',
                'shortname' => 'AfterpayInvoice',
                'description' => 'First Cash Solution Afterpay Rechnung',
                'action' => 'FatchipFCSAfterpay',
                'template' => 'fatchip_firstcash_afterpay_invoice.tpl',
                'additionalDescription' => '',
                'className' => 'Afterpay',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],*/
/*            [
                'name' => 'fatchip_firstcash_afterpay_installment',
                'shortname' => 'AfterpayInstallment',
                'description' => 'First Cash Solution Afterpay Ratenzahlung',
                'action' => 'FatchipFCSAfterpay',
                'template' => 'fatchip_firstcash_afterpay_installment.tpl',
                'additionalDescription' => '',
                'className' => 'Afterpay',
                //'countries' => ['DE', 'NL', 'DK', 'FI', 'SE', 'NO'],
            ],
*/
        ];
}
